# Zoho-assignments.c
#include<stdio.h>
#include<stdlib.h>
#include<string.h>
int main()
{
    char *number;
    char rough[100];
    int length,looprunner,i,j,d1,d2,flag=0,flag1=0,flag2=5;
    int d3,d4;
    int k,l;
    printf("Enter the number:\n");
    scanf("%s",rough);
    length=strlen(rough);
    number=(char *)malloc(length*sizeof(char));
    i=0;
    while(i<length)
    {
        number[i]=rough[i];
        i++;
    }
    number[i]='\0';
    if(length%2!=0)
    {
        looprunner=length/2+1;
    }
    else
    {
        looprunner=length/2;
    }
    j=length-1;
    i=0;
    if(length==1)
    {
        k=(int)(number[0]-'0');
        if(k<9)
        {
            printf("%d",(k+1));
            return 0;
        }
    }
    while(i<looprunner)
    {
        d1=(int)(number[i]-'0');
        d2=(int)(number[j]-'0');
        if(flag1==1)
        {
            if(d1>d2)
            {
                d2=d1;
                number[j]=(char)(d2+'0');
                flag1=0;
                break;
            }
            if(d1<d2)
            {
                d1=d1+1;
                d2=d1;
                number[i]=(char)(d1+'0');
                number[j]=(char)(d1+'0');
                flag1=0;
                break;
            }
            if(d1==d2)
            {
                if(i!=0)
                {
                    d3=(int)(rough[i]-'0');
                    d4=(int)(rough[j]-'0');
                    if((d3!=d4)&&(d4>d3))
                    {
                        flag1=0;
                        break;
                    }
                }
                if(d1!=9)
                {
                    d1=d1+1;
                    d2=d2+1;
                    number[i]=(char)(d1+'0');
                    number[j]=(char)(d1+'0');
                    flag1=0;
                    break;
                }
                else
                {
                    if((d3!=9)||(d4!=9))
                    {
                        k=i+1;
                        l=j-1;
                        flag2=1;
                        while(k<looprunner)
                        {
                            d3=(int)(rough[k]-'0');
                            d4=(int)(rough[l]-'0');
                            if((d3!=9)||(d4!=9))
                            {
                                flag2=0;
                                break;
                            }
                            k++;
                            l--;
                        }
                        if(flag2==1)
                        {
                            k=i+1;
                            l=j-1;
                            while(k<looprunner)
                            {
                                number[k]=(char)(9+'0');
                                number[l]=(char)(9+'0');
                                k++;
                                l--;
                            }
                            flag2=0;
                            break;
                        }
                    }
                    d1=0;
                    d2=0;
                    number[i]=(char)(d1+'0');
                    number[j]=(char)(d2+'0');
                    i--;
                    j++;
                    if(i==-1)
                    {
                        flag1=0;
                        continue;
                    }
                    else
                    {
                        continue;
                    }
                }
            }
        }
        if(i==-1)
        {
            flag=1;
            length=length+1;
            number=(char *)realloc(number,length*sizeof(char));
            for(i=0;i<length;i++)
            {
                if(i==0)
                {
                    number[i]=(char)(1+'0');
                }
                else
                {
                    number[i]=(char)(0+'0');
                }
            }
            number[i]='\0';
            i=0;
            j=length-1;
            if(length%2!=0)
            {
                looprunner=length/2+1;
            }
            else
            {
                looprunner=length/2;
            }
            continue;
        }
        if(i==(looprunner-1))
        {
            if((flag==1)&&(i==0))
            {
                d2=d1;
                number[j]=(char)(d2+'0');
                i++;
                j--;
                flag=0;
                continue;
            }
            if(flag==1)
            {
                i++;
                flag=0;
                continue;
            }
            if(d1>d2)
            {
                d2=d1;
                number[j]=(char)(d2+'0');
                i++;
                j--;
                continue;
            }
            if(d1<d2)
            {
            	d1=d1+1;
                d2=d1;
            	number[i]=(char)(d1+'0');
                number[j]=(char)(d2+'0');
            	i++;
            	j--;
            	continue;
            }
            if(d1==d2)
            {
                if(d1!=9)
                {
                    k=i-1;
                    l=j+1;
                    flag2=1;
                    while(k>0)
                    {
                        d3=(int)(rough[k]-'0');
                        d4=(int)(rough[l]-'0');
                        if(d3<d4)
                        {
                            flag2=0;
                            break;
                        }
                        k--;
                        l++;
                    }
                    if(flag2==1)
                    {
                        i++;
                        j--;
                        continue;
                    }
                    d1=d1+1;
                    d2=d2+1;
                    number[i]=(char)(d1+'0');
                    number[j]=(char)(d2+'0');
                    k=i-1;
                    l=j+1;
                    flag2=1;
                    while(k>0)
                    {
                        d3=(int)(rough[k]-'0');
                        d4=(int)(rough[l]-'0');
                        if(d3<d4)
                        {
                            d4=d3;
                            number[k]=(char)(d3+'0');
                            number[l]=(char)(d4+'0');
                        }
                        k--;
                        l++;
                    }
                    i++;
                    j--;
                    continue;
                }
                else
                {
                    d1=0;
                    d2=0;
                    number[i]=(char)(d1+'0');
                    number[j]=(char)(d2+'0');
                    i--;
                    j++;
                    if(i!=-1)
                    {
                        flag1=1;
                    }
                    continue;
                }
            }
        }
        if(i==0)
        {
            d2=d1;
            number[i]=(char)(d1+'0');
            number[j]=(char)(d2+'0');
            i++;
            j--;
            continue;
        }
        else
        {
            if(d1>d2)
            {
                d2=d1;
                number[i]=(char)(d1+'0');
                number[j]=(char)(d2+'0');
                i++;
                j--;
                continue;
            }
            if(d1<d2)
            {
                d1=d1+1;
                d2=d1;
                number[i]=(char)(d1+'0');
                number[j]=(char)(d2+'0');
                i++;
                j--;
                continue;
            }
            if(d1==d2)
            {
                i++;
                j--;
                continue;
            }
        }
    }
    for(i=0;i<length;i++)
    {
        printf("%c",number[i]);
    }
    return 0;
}
